### ISSUE TITLE
Using View doesn't let xcode run : Viewer Issue

### ISSUE THREAD

**Issue by sharadchauhan0504** [bakkenbaeck/Viewer#116]
Hello, 

I have tried installing viewer using cocoapods and by coping main source file. But none of them is working. 
Whenever i am trying to build the project, xcode is getting crashed. After removing Viewer that didn't happen. So because of this i am unable to use viewer.
Please look into this issue and provide some guidation. 
Thanks.

**Comment by elland** [comment]
Hey @skdevil what was the issue? Did you solve it?
