### ISSUE TITLE
Some performance issues during paginating

### ISSUE THREAD

**Issue by seidju** [bakkenbaeck/Viewer#118]
Hi! First of all thanks for a great library! 
I found some small issue while paginating between photos. It's seems like when changing current indexPath, there's some image request appears, so viewer lags a little bit and photo blinks.

I attached small video for demonstration. 
https://www.dropbox.com/s/v7tmu0w7n2kzn09/viewer_bug.mp4?dl=0

**Comment by 3lvis** [comment]
@seidju Hi! The sample project could be improved to load images in the background, but its main goal is just to show the basics of how to use the library, image loading is meant to be done by your app, the library only takes care of displaying the images.

**Comment by seidju** [comment]
Ok, will look into fetching options, thanks anyway! )
