### ISSUE TITLE
iOS compile error on VideoView.swift

### ISSUE THREAD

**Issue by doraeminemon** [bakkenbaeck/Viewer#123]
Using Cocoapods with version 3.0.0 
Compile error on line 27 
https://github.com/bakkenbaeck/Viewer/blob/master/Source/VideoView.swift#L27
```
        #if os(tvOS)
            playerLayer.videoGravity = AVLayerVideoGravity.resizeAspectFill
        #else
            playerLayer.videoGravity = AVLayerVideoGravity.resizeAspectFill <<< 
        #endif
```
### Error : 
Type 'AVLayerVideoGravity' (aka 'NSString') has no member 'resizeAspectFill'

**Comment by elland** [comment]
@doraeminemon could you try building from #124 and see what happens? 🤞🏽

**Comment by askeland** [comment]
Actually the whole VideoView should be iOS only. On tvOS we use AVPlayerViewController instead of VideoView.
