### ISSUE TITLE
Swift 5.0 compatibility

### ISSUE THREAD

**Issue by RobSwish** [bakkenbaeck/Viewer#135]
I'm pulling from 'https://github.com/3lvis/Viewer.git', :commit => 'baaf8ca0c3e93c3a08288c1bdf52116444d20ee8', which seems to work but would be nice to pull from release.

**Comment by 3lvis** [comment]
Hi Rob!

Should be published as Viewer 4.0 in CocoaPods, let me know if doesn't work :)

**Comment by tiwari1amrit** [comment]
@3lvis Hello Can you please make it compatible on swift 5.0?

**Comment by 3lvis** [comment]
Yes!

**Comment by 3lvis** [comment]
https://github.com/3lvis/Viewer/releases/tag/4.0.0
