### ISSUE TITLE
video play icon not hidden swipe back when "video autoplay" true. 

### ISSUE THREAD

**Issue by DixPatel009** [bakkenbaeck/Viewer#140]
Hi! That's really a great library.
i just post this issue(inform) here because of you make this library much better.
i am using Xcode 11.0 and swift 4.0 or above.
i am getting issue when i used local option on your demo and also my project.

**Comment by 3lvis** [comment]
Hi @DixPatel009! I was able to reproduce this issue. Thanks for reporting it.

**Comment by 3lvis** [comment]
https://github.com/3lvis/Viewer/pull/144

**Comment by DixPatel009** [comment]
@3lvis  Thank you :)
