### ISSUE TITLE
Conforming to Viewable?

### ISSUE THREAD

**Issue by rigaldamez** [bakkenbaeck/Viewer#141]
apologies as this is more of a "how-to"....I have an imageURL string, how can I conform to the Viewable protocol?

**Comment by MaciejGad** [comment]
Probably that you are the one who asked the question on SO, but maybe it will be helpful for others: https://stackoverflow.com/a/58180184/1797194  
also, you can check the implementation in Photo class https://github.com/3lvis/Viewer/blob/master/Library/Photo.swift but it is more complicated

**Comment by MaciejGad** [comment]
Also there is a response from the library creator: https://github.com/3lvis/Viewer/issues/136

**Comment by rigaldamez** [comment]
thanks for your help, i have managed to get it to work. Although I am not seeing a loading indicator or an icon to dismiss the view (I know)?
