### ISSUE TITLE
How can we know which Viewable object the user has initiated an action for in the footer / header?

### ISSUE THREAD

**Issue by rob-burrus** [bakkenbaeck/Viewer#146]
If the user can change from the initialIndexPath, how do we know which Viewable object a header / footer action is occurring?  Say I wanted to favorite or delete an photo as in the example, how do we know which photo this is happening to?

**Comment by rob-burrus** [comment]
Just kidding, I see now that we can look at the viewerController.currentIndexPath

**Comment by 3lvis** [comment]
I'm glad you got it working, @rob-burrus!
