### ISSUE TITLE
If you have turned your phone on silent, the videos does not play with sound

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/Viewer#68]
# Steps to reproduce
- Put your phone on silent mode
- Select a video
# Expected
- Plays with sounds
# Current
- Doesn't play with sound

**Comment by 3lvis** [comment]
In Snapchat, the video plays without sound and sound just starts after you try to raise the volume. I like this behavior since there's a reason why your phone is in silent mode, it shouldn't assume that you want sound all the time.

**Comment by askeland** [comment]
Fixed in https://github.com/bakkenbaeck/Viewer/pull/95
