### ISSUE TITLE
Carthage: Skipped building Viewer due to the error

### ISSUE THREAD

**Issue by wousser** [bakkenbaeck/Viewer#98]
Most recent version can not be build by Carthage:
*** Skipped building Viewer due to the error:
Dependency "Viewer" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at Optional("https://github.com/bakkenbaeck/Viewer/issues/new")

**Comment by petrovi4** [comment]
Dear maintainer, please add support for Carthage

**Comment by petrovi4** [comment]
Please, approve PR https://github.com/3lvis/Viewer/pull/139 for Carthage support

**Comment by 3lvis** [comment]
Carthage supported!
